### ISSUE TITLE
Lack of  file "dataset_instructions" and 'LanguageWithAttentionSUM_model.pt'

### ISSUE THREAD

**Issue by HarryHsing** [valeriechen/ask-your-humans#2]

**Comment by HarryHsing** [comment]
Hi, I cannot find 'dataset_instructions' anywhere, besides, 'LanguageWithAttentionSUM_model.pt' is also missing/

**Comment by valeriechen** [comment]
Hi! You can find 'dataset_instructions' in dataset split.zip [here](https://drive.google.com/drive/u/4/folders/1R7BtnlmF6nejGplXvaqs7OjoJ9a5zbJj).

I don't currently have 'LanguageWithAttentionSUM_model.pt' but if you have access to GPU you can train the same model using 'train_hierarchy.py' (this does the IL training portion on our model).

**Comment by HarryHsing** [comment]
> Hi! You can find 'dataset_instructions' in dataset split.zip [here](https://drive.google.com/drive/u/4/folders/1R7BtnlmF6nejGplXvaqs7OjoJ9a5zbJj).
> 
> I don't currently have 'LanguageWithAttentionSUM_model.pt' but if you have access to GPU you can train the same model using 'train_hierarchy.py' (this does the IL training portion on our model).

Thanks a lot, Valerie! I am wondering is it ok to train the model using 'train_hierarchy.py'  on CPU since I don't have access to GPU now.

As I don't find data_instructions in dataset split.zip, I use data_all_instructions instead. And this is the error I met when training on a CPU using 'train_hierarchy.py'

`
Traceback (most recent call last):
  File "train_hierarchy.py", line 433, in <module>
    train_step_both(epoch)
  File "train_hierarchy.py", line 336, in train_step_both
    for i, data in enumerate(train_loader, 0):
  File "/Users/xingzhenghao/opt/anaconda3/envs/webank/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/Users/xingzhenghao/opt/anaconda3/envs/webank/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/Users/xingzhenghao/opt/anaconda3/envs/webank/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/xingzhenghao/opt/anaconda3/envs/webank/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "train_hierarchy.py", line 195, in __getitem__
    temp_instruction = self.train_instructions[index]
IndexError: list index out of range
` 

Probably because they don't share the same dimension (train_instructions is actually train_all_instructions here, as I don't find train_instructions): 
`
train_states length:  202831
train_inventories length:  202831
train_actions :length  202831
train_goals length:  202831
train_instructions length:  35921
`

**Comment by valeriechen** [comment]
Hey! I updated dataset split.zip so you should find all of the necessary files in there now. And I think you should be able to use CPU, it will just take longer to train.

**Comment by jhejna** [comment]
Hi! It seems like the `dataset split.zip` was modified, but the `dataset_instructions` file still appears to be missing. Thanks!

**Comment by HarryHsing** [comment]
> Hey! I updated dataset split.zip so you should find all of the necessary files in there now. And I think you should be able to use CPU, it will just take longer to train.

Thanks very much for your support, but `dataset_instructions`  file is still missing, thus I cannot train `LanguageWithAttentionSUM_model.pt `by myself. ;)

**Comment by valeriechen** [comment]
Hi both, please try again and let me know if you cannot find it.
